engine/engine/config/routes.rb
Rails.application.routes.draw do

  root 									 'static_pages#home'
  get 'contact' 			=> 'static_pages#contact'
  get 'help' 					=> 'static_pages#help'
  get 'about' 				=> 'static_pages#about'
  get 'signup'				=> 'users#new'
	get	'admin'					=> 'settings#edit'
	get 'login'		  		=> 'sessions#new'
	get 'scoreboard'		=> 'scoreboard#index'

	get 'teams/get_score_data' => 'scoreboard#get_score_data'
	get 'users/get_stats'			 => 'users#get_stats'
	get 'users/:id/checkout'	 => 'users#checkout', as: 'checkout'

	post 'login' 		 			=> 'sessions#create'
	post 'request_hint' 	=> 'hint_requests#create'
	post 'submit' 				=> 'submissions#create'
	post 'join'       		=> 'teams#join'
	post 'remove_member'	=> 'teams#remove_member'
	post 'add_hint'				=> 'hints#new'

	post 'problems/add_hint' => 'problems#add_hint'
	post 'users/:id/charge'	 => 'users#charge', as: 'charge'

	delete 'logout'					=> 'sessions#destroy'
	delete 'remove_hint'		=> 'problems#remove_hint'
	delete 'remove_bracket'	=> 'brackets#destroy'

	patch 'settings' => 'settings#update'

	resources :users
	resources :problems
	resources :teams
	resources :charges
	resources :account_activations, only: [:edit]
	resources :hints,								only: [:new, :edit, :create, :update]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :brackets,						only: [:new, :create, :edit, :update]

end

engine/engine/app/models/setting.rb
class ValidateDates < ActiveModel::Validator
  def validate(record)
    if record.setting_type == 'date' && !DateTime.strptime(record.value, '%m/%d/%Y %I:%M %p')
      record.errors[] << 'Invalid date'
    end
  end
end

class Setting < ActiveRecord::Base
	validates :name, presence: true, length: { maximum: 255 }, uniqueness: true
	validates :setting_type, presence: true, length: { maximum: 255 }
	validates_with ValidateDates
end

engine/engine/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	before_action :admin_user, only: [:index, :edit, :update]

	def edit
		@categories = Setting.uniq.pluck(:category).sort
		@settings = Setting.all.order(category: :asc, id: :asc)
		@brackets = Bracket.all.order('priority ASC')
		@users = User.all
		@teams = Team.all
	end
	
	def update
		error = false
		settings = params[:admin]
		for setting in settings
			setting = setting[1]
			to_update = Setting.find(setting[:id])

			if to_update.setting_type == 'boolean'
 				to_update.value = (setting[:value]) ? "1" : "0"
			else
				to_update.value = setting[:value]
			end

			error = (to_update.save) ? false : true
		end

		if error
			flash[:danger] = "Failed to update database. Try again."
		else
			flash[:success] = "Successfully updated changes."
		end
		redirect_to admin_url
	end

	private
		def admin_user
      unless logged_in? && current_user.admin?
				store_location
				flash[:danger] = "Access Denied."
				redirect_to root_url
			end
    end
end

engine/engine/app/helpers/settings_helper.rb
module SettingsHelper
	def competition_started?
		start_time = DateTime.strptime(Setting.find_by(name: 'start_time').value, '%m/%d/%Y %I:%M %p')
		DateTime.current.to_i > start_time.to_i
	end
	
	def competition_ended?
		end_time = DateTime.strptime(Setting.find_by(name: 'end_time').value, '%m/%d/%Y %I:%M %p')
		DateTime.current.to_i > end_time.to_i
	end

	def competition_active?
		competition_started? && !competition_ended?
	end

	def competition_name
		Setting.find_by(name: 'competition_name').value
	end

	def subtract_hint_points_before_solve?
		(Setting.find_by(name: 'subtract_hint_points_before_solve').value == "0") ? false : true
	end

	def scoreboard_on?
		(Setting.find_by(name: 'scoreboard_on').value == "0") ? false : true
	end

	def send_activation_emails?
		(Setting.find_by(name: 'send_activation_emails').value == "0") ? false : true
	end

	def view_other_profiles?
		(Setting.find_by(name: 'view_other_profiles').value == "0") ? false : true
	end

	def use_handicap?
		(Setting.find_by(name: 'use_bracket_handicaps').value == "0") ? false : true
	end

	def require_payment?
		(Setting.find_by(name: 'require_payment').value == "0") ? false : true
	end

	def registration_active?
		(Setting.find_by(name: 'registration_active').value == "0") ? false : true
	end

	def entry_cost
		Setting.find_by(name: 'entry_cost').value
	end

	def fifty_percent_off
		Setting.find_by(name: 'fifty_percent_off').value
	end

	def one_hundred_percent_off
		Setting.find_by(name: 'one_hundred_percent_off').value
	end

	# returns int value of setting if it's between 0 and 2 ^ 16, otherwise 0
	# 0 = no limit on submissions
	def max_submissions_per_team
		(value = Setting.find_by(name: 'max_submissions_per_team').value.to_i).between?(0,2**16) ? value : 0
	end

end

engine/engine/app/views/settings/_brackets.html.erb
<% if @brackets %>
	<%= content_tag :table, id: 'brackets', class: 'table' do %>
		<%= content_tag :thead do %>
			<%= content_tag :tr do %>
				<%= content_tag :td, 'Name' %>
				<%= content_tag :td, 'Priority' %>
				<%= content_tag :td, 'Options' %>
			<% end %>
		<% end %>
		<%= content_tag :tbody do %>
			<% for bracket in @brackets do %>
				<%= content_tag :tr do %>
					<%= content_tag :td, bracket.name %>
					<%= content_tag :td, bracket.priority %>
					<%= content_tag :td do %>
						<%= link_to 'Edit', edit_bracket_path(bracket.id), class: 'btn btn-primary' %>
						<%= link_to 'Remove', remove_bracket_path(id: bracket),  method: :delete, class: 'btn btn-primary' %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
<% end %>
<%= link_to 'Create', new_bracket_path, class: 'btn btn-primary' %>

engine/engine/app/views/settings/_form.html.erb
<%= form_tag settings_path, method: 'patch', class: 'form-inline col-md-12' do %>

	<!-- Nav tabs -->
	<%= content_tag :ul, class: 'nav nav-tabs', role: 'tablist' do %>
		<% for @category in @categories %>
			<%= content_tag :li, class: ((@category == @categories.first) ? 'active' : '') do %>
				<%= content_tag :a, href: "##{@category}", 'aria-controls' => "#{@category}", role: 'tab', 'data-toggle' => 'tab' do %>
					<%= @category %>
				<% end %>
			<% end %>
		<% end %>
		<%= content_tag :li do %>
			<%= content_tag :a, 'Brackets', href: "#brackets", 'aria-controls' => "brackets", role: 'tab', 'data-toggle' => 'tab' %>
		<% end %>
		<%= content_tag :li do %>
			<%= content_tag :a, 'Teams', href: "#teams", 'aria-controls' => "teams", role: 'tab', 'data-toggle' => 'tab' %>
		<% end %>
		<%= content_tag :li do %>
			<%= content_tag :a, 'Users', href: "#users", 'aria-controls' => "users", role: 'tab', 'data-toggle' => 'tab' %>
		<% end %>

		<%= content_tag :div, id: 'filter_container', class: 'input-group pull-right', style: 'display:none' do %>
			<%= content_tag :span, 'Search', class: 'input-group-addon' %>
			<input id="filter" type="text" class="filter form-control">
		<% end %>
	<% end %>

	<!-- Tab panes -->
	<%= content_tag :div, class: 'tab-content' do %>
		<% for @category in @categories %>
			<%= content_tag :div, class: "tab-pane #{((@category == @categories.first) ? 'active' : '')}", id: @category do %>

				<% @cat_settings = @settings.where(category: @category) %>
				<% for @setting in @cat_settings %>
					<%= content_tag :div, class: 'row settings-row' do %>

						<% # Switches for boolean settings # %>
						<% if @setting.setting_type == 'boolean' %>
							<%= hidden_field_tag "admin[#{@setting.id.to_s}][id]", :id, value: @setting.id %>
							<%= content_tag :div, class: 'col-md-4' do %>
								<%= label_tag nil, @setting.label, class: 'control-label' %>
								<%= tag :br %>
								<%= content_tag :small, @setting.tooltip, class: 'text-muted' %>
							<% end %>
							<%  checked = (@setting.value == '1') ? true : false %>
							<%= check_box_tag "admin[#{@setting.id.to_s}][value]", @setting.value, checked, class: 'col-md-8 bootstrap-switches' %>

						<% # Color picker for 'color' settings # %>
						<% #elsif @setting.setting_type == 'color' %>
			
						<% # Datetime picker for 'date' settings # %>
						<% elsif @setting.setting_type == 'date' %>
							<%= hidden_field_tag "admin[#{@setting.id.to_s}][id]", :id, value: @setting.id %>
							<%= content_tag :div, class: 'col-md-4' do %>
								<%= label_tag nil, @setting.label, class: 'control-label' %>
								<%= tag :br %>
								<%= content_tag :small, @setting.tooltip, class: 'text-muted' %>
							<% end %>

							<%= content_tag :div, class: 'form-group' do %>
								<%= content_tag :div, class: 'input-group date', id: add_id('datetimepicker',@setting) do %>
									<%= text_field "admin[#{@setting.id.to_s}]", 'value', value: @setting.value, class: 'col-md-8 form-control' %>
									<%= content_tag :span, class: 'input-group-addon' do %>
										<%= content_tag :span, nil, class: 'glyphicon glyphicon-calendar' %>
									<% end %>
								<% end %>
							<% end %>
							<%= javascript_tag do %>
								$('#datetimepicker_<%= @setting.id %>').datetimepicker();
							<% end %>

						<% # Text box for standard text settings # %>
						<% else #setting.setting_type == 'text' %>
							<%= hidden_field_tag "admin[#{@setting.id.to_s}][id]", :id, value: @setting.id %>
							<%= content_tag :div, class: 'col-md-4' do %>
								<%= label_tag nil, @setting.label, class: 'control-label' %>
								<%= tag :br %>
								<%= content_tag :small, @setting.tooltip, class: 'text-muted' %>
							<% end %>
							<%= text_field "admin[#{@setting.id.to_s}]", 'value', value: @setting.value, class: 'col-md-8 form-control' %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
		
		<%= content_tag :div, class: 'tab-pane', id: 'brackets' do %>
			<%= render 'brackets' %>
		<% end %>
		<%= content_tag :div, class: 'tab-pane', id: 'teams' do %>
			<%= content_tag :h4, "Count: #{@teams.count}", class: 'text-center' %>
			<%= content_tag :ul, class: 'teams row filter_list' do %>
				<%= render @teams %>
			<% end %>
		<% end %>
		<%= content_tag :div, class: 'tab-pane', id: 'users' do %>
			<%= content_tag :h4, "Count: #{@users.count}", class: 'text-center' %>
			<%= content_tag :ul, class: 'users row filter_list' do %>
				<%= render @users %>
			<% end %>
		<% end %>
	<% end %>

	<%= tag :br %>
	<%= submit_tag 'Save Changes', class: 'form-control col-md-3 btn btn-primary' %>

<% end %>

engine/engine/app/views/settings/edit.html.erb
<% provide(:title, 'Admin Console') %>
<%= content_tag :h1, 'Settings' %>
<%= content_tag :div, id: 'settings', class: 'row' do %>
	<%= render 'form' %>
<% end %>