engine/engine/config/routes.rb
Rails.application.routes.draw do

  root 									 'static_pages#home'
  get 'contact' 			=> 'static_pages#contact'
  get 'help' 					=> 'static_pages#help'
  get 'about' 				=> 'static_pages#about'
  get 'signup'				=> 'users#new'
	get	'admin'					=> 'settings#edit'
	get 'login'		  		=> 'sessions#new'
	get 'scoreboard'		=> 'scoreboard#index'

	get 'teams/get_score_data' => 'scoreboard#get_score_data'
	get 'users/get_stats'			 => 'users#get_stats'
	get 'users/:id/checkout'	 => 'users#checkout', as: 'checkout'

	post 'login' 		 			=> 'sessions#create'
	post 'request_hint' 	=> 'hint_requests#create'
	post 'submit' 				=> 'submissions#create'
	post 'join'       		=> 'teams#join'
	post 'remove_member'	=> 'teams#remove_member'
	post 'add_hint'				=> 'hints#new'

	post 'problems/add_hint' => 'problems#add_hint'
	post 'users/:id/charge'	 => 'users#charge', as: 'charge'

	delete 'logout'					=> 'sessions#destroy'
	delete 'remove_hint'		=> 'problems#remove_hint'
	delete 'remove_bracket'	=> 'brackets#destroy'

	patch 'settings' => 'settings#update'

	resources :users
	resources :problems
	resources :teams
	resources :charges
	resources :account_activations, only: [:edit]
	resources :hints,								only: [:new, :edit, :create, :update]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :brackets,						only: [:new, :create, :edit, :update]

end

engine/engine/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def help
  end

	def about
	end
end

engine/engine/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

engine/engine/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>This is a scoring server built using Ruby on Rails by the Military Cyber Professionals Association (MCPA). It is free to use and extend under the MIT license (see LICENSE file). The goal of this project is to provide a standard generic scoring server that provides an easy way to add and modify problems and track statistics of a Cyber Capture the Flag event. While it's not recommended, this server can be hosted with your challenges but we do recommend sand-boxing your challenges so they do not affect the scoring server.</p>

<p>If you have questions please visit our Github page <a href="https://github.com/mcpa-stlouis/hack-the-arch">here</a>.</p>

engine/engine/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>This app was developed by the Military Cyber Professionals Association - St. Louis Chapter.  They can be reached at <a href="mailto:contact.stlouis@milcyber.org">contact.stlouis@milcyber.org</a></p>

engine/engine/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p><b>After signing up:</b> <%= link_to "create", new_team_path %> or <%= link_to "join", teams_path %> a team.  If joining an existing team, just navigate to the team view and enter the passphrase and click join.  After joining a team, you can view and solve challenges!</p>
<p><b>What is a CTF?:</b> A CTF is an event during which students, teachers, and professionals come together to compete against one another in an effort to test and expand cyber-security skills and awareness. Participants will be challenged with cyber-security related puzzles from categories like network exploitation, cyber forensics, cryptography, and cyber trivia. Each challenge hides a unique string called a 'flag' and participants will receive points for each captured flag.</p>
<p><b>Questions:</b> If you have any further questions, please contact the competition admin.</p>

engine/engine/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to <%= competition_name %></h1>

	<div class="row">
	<%= link_to image_tag("mcpa-black.png", width: '80%', alt: "MCPA St. Louis logo", 
												class: "center col-sm-12 col-md-6 col-md-offset-3"), 'http://mcpa-stl.org' %>
	</div>
  <h2>
    This is the home page for the 
    <a href="https://github.com/mcpa-stlouis/hack-the-arch">HackTheArch</a>
    scoring server application developed by the Military Cyber Professionals Association - St. Louis Chapter.
  </h2>

	<% if registration_active? %>
		<% if !logged_in? %>
  			<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  		<% end %>
	<% else %>
		<% if competition_started? %>
			<h3>Registration closed!</h3>
		<% else %>
			<h3>Registration hasn't opened yet, check back soon!</h3>
		<% end %>
	<% end %>
</div>