engine/engine/config/routes.rb
Rails.application.routes.draw do

  root 									 'static_pages#home'
  get 'contact' 			=> 'static_pages#contact'
  get 'help' 					=> 'static_pages#help'
  get 'about' 				=> 'static_pages#about'
  get 'signup'				=> 'users#new'
	get	'admin'					=> 'settings#edit'
	get 'login'		  		=> 'sessions#new'
	get 'scoreboard'		=> 'scoreboard#index'

	get 'teams/get_score_data' => 'scoreboard#get_score_data'
	get 'users/get_stats'			 => 'users#get_stats'
	get 'users/:id/checkout'	 => 'users#checkout', as: 'checkout'

	post 'login' 		 			=> 'sessions#create'
	post 'request_hint' 	=> 'hint_requests#create'
	post 'submit' 				=> 'submissions#create'
	post 'join'       		=> 'teams#join'
	post 'remove_member'	=> 'teams#remove_member'
	post 'add_hint'				=> 'hints#new'

	post 'problems/add_hint' => 'problems#add_hint'
	post 'users/:id/charge'	 => 'users#charge', as: 'charge'

	delete 'logout'					=> 'sessions#destroy'
	delete 'remove_hint'		=> 'problems#remove_hint'
	delete 'remove_bracket'	=> 'brackets#destroy'

	patch 'settings' => 'settings#update'

	resources :users
	resources :problems
	resources :teams
	resources :charges
	resources :account_activations, only: [:edit]
	resources :hints,								only: [:new, :edit, :create, :update]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	resources :brackets,						only: [:new, :create, :edit, :update]

end

engine/engine/app/models/user.rb
class User < ActiveRecord::Base
	include SettingsHelper
	attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
	belongs_to :team
	has_many :submissions, dependent: :destroy, inverse_of: :user
	has_many :hint_requests, dependent: :destroy, inverse_of: :user
	validates :fname,  presence: true, length: { maximum: 50 }
	validates :lname,  presence: true, length: { maximum: 50 }
	validates :username, presence: true, length: { maximum: 128 }, 
											 uniqueness: {case_sensitive: true}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum:6 }, allow_nil: true

	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def is_member?(team)
		self.team_id == team.id
	end

	def leave_team
		update_attribute(:team_id, nil)
	end

	def join_team(team)
		update_attribute(:team_id, team.id)
	end

	def remember
		self.remember_token = User.new_token
		update_attribute :remember_digest, User.digest(remember_token)
	end

	def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

	def forget
		update_attribute :remember_digest, nil
	end

	def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    update_attribute(:activation_digest,  User.digest(activation_token))
  end

	def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

	def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

	def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
	
	def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

	def get_score
		cache = Cache.find_by(key: 'user_'+self.id.to_s+'_score')
		if cache && cache.cache_valid
			cache.value.to_i
		else
			if subtract_hint_points_before_solve?
				score = Submission.where(user_id: self.id).sum(:points) - 
				HintRequest.where(user_id: self.id).sum(:points)
			else
				score = 0
				for submission in Submission.where(user_id: self.id)
					if submission.correct
						score = score + submission.points
						for hint in HintRequest.where(user_id: self.id, problem_id: submission.problem_id)
							score = score - hint.points
						end
					end
				end
			end

			# Update cache
			if cache 
				cache.update(score)
			else
				Cache.create(key: 'user_'+self.id.to_s+'_score', value: score, cache_valid: true)
			end
			score
		end
	end

	def invalidate_score
		cache = Cache.find_by(key: 'user_'+self.id.to_s+'_score')
		if cache
			cache.invalidate
		end
	end

	def get_accuracy_data
		result = Array.new

		result.push(['Correct', self.submissions.where(correct: true).count])
		result.push(['Incorrect', self.submissions.where.not(correct: true).count])

		result
	end

	def get_category_data
		result = Array.new
		@intermediate_result = Hash.new
		@categories = Problem.select(:category).distinct
		@subs = self.submissions.where(correct: true)
		@category = ""
		@count = 0

		for @category in @categories
			@intermediate_result[@category.category] = 0
		end

		for @sub in @subs
			@intermediate_result[@sub.problem.category] += 1
		end

		@intermediate_result.each do |key, value|
			result.push([key, value])
		end
		result

	end

	private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

end

engine/engine/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:show, :index, :destroy, :edit, :update, :get_stats]
	before_action :registration_active, only: [:new, :create]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: [:index, :destroy]
	before_action :require_payment, only: [:checkout, :charge]

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		user = User.find(params[:id])
		if user.activated? 
			if view_other_profiles? || current_user?(user) || admin_user?
				@user = user
				@score = @user.get_score
				@submissions = @user.submissions
				@number_of_correct_submissions = @submissions.where(correct: true).count
				@total_number_of_submissions = @submissions.count
				@accuracy = (@total_number_of_submissions == 0) ? 0 : @number_of_correct_submissions.to_f/@total_number_of_submissions.to_f
				@number_of_hints = @user.hint_requests.count
 			else
      	message  = "Access Denied. "
      	message += "You can only view your profile."
      	flash[:warning] = message
  			redirect_to root_url
  		end
		else
      message  = "Account not activated. "
			if current_user?(user)
      	message += "Check your email for the activation link."
			end
      flash[:warning] = message
			redirect_to root_url
		end
	end

	def get_stats
		if @user = User.find_by_id(params[:id])

			@accuracy_data = @user.get_accuracy_data
			@category_data = @user.get_category_data
			render :json => { accuracy_data: @accuracy_data.to_json.html_safe, 
												category_data: @category_data.to_json.html_safe, 
												status: :ok}
		else
      flash[:warning] = "No such user"
			redirect_to root_url
		end
	end

  def new
		@user = User.new
  end

	def create
		@user = User.new(user_params)
		if @user.save || ( @user.id && User.find(@user) && !@user.paid )
			if require_payment?
				redirect_to checkout_path(@user)
			else
				activate_user(@user)
			end
		else
			render 'new'
		end
	end

	def checkout
		if params[:id]
			@user = User.find(params[:id])
			@cost = entry_cost.to_f
			@discount = 0.00

      if @user && @user.activated
        redirect_to root_url
      end

			if !one_hundred_percent_off.blank? && @user.discount_code == one_hundred_percent_off
				activate_user(@user)
			elsif !fifty_percent_off.blank? && @user.discount_code == fifty_percent_off
				@discount = @cost / 2
			end

		else
			flash[:danger] = "You must begin registration before checking out"
			redirect_to root_url
		end
	end

	def charge
		@user = User.find(params[:user_id])
		if @user && @user.paid
			flash[:info] = "You have already paid!"
			redirect_to @user
		end

		@cost = entry_cost.to_f

		if !fifty_percent_off.blank? && @user.discount_code == fifty_percent_off
			@cost = @cost / 2
		end
		
  	customer = Stripe::Customer.create(
   		:email => params[:stripeEmail],
   		:source  => params[:stripeToken]
  	)
	
  	charge = Stripe::Charge.create(
   		:customer    => customer.id,
   		:amount      => @cost.to_i.to_s,
   		:description => "#{competition_name} registration for: #{@user.email}",
   		:currency    => 'usd'
  	)

		activate_user(@user)

		rescue Stripe::CardError => e
  		flash[:error] = e.message
  		redirect_to checkout_path(@user)

	end

	def destroy
		User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
	end

	def edit
		@edit_user_page = true
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Changes saved successfully"
			redirect_to @user
		else
			render 'edit'
		end
	end

	private
		def user_params
			params.require(:user).permit(:fname, :lname, :username, :email, :password, :password_confirmation, :discount_code)
		end

		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please log in."
				redirect_to login_url
			end
		end

		def require_payment
			unless require_payment?
				flash[:danger] = "Access denied"
				redirect_to root_url
			end
		end
		
		def correct_user
			@user = User.find(params[:id])
			unless current_user?(@user)
				flash[:danger] = "Access denied"
				redirect_to root_url
			end
		end

		def admin_user
    	unless admin_user?
				flash[:danger] = "Access denied"
				redirect_to root_url
			end
    end

		def activate_user(user)
			user.update_attributes(paid: true)
	
			if send_activation_emails?
  			user.create_activation_digest
				user.send_activation_email
    		flash[:info] = "Please check your email to activate your account."
    		redirect_to root_url
			else
				user.activate
				log_in(user)
    		flash[:success] = "Welcome to #{competition_name}!"
    		redirect_to user
			end
		end

		def registration_active
			unless registration_active?
				flash[:info] = "Registration is not open"
				redirect_to root_url
			end
		end

end

engine/engine/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
	def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.fname, class: "gravatar")
  end

end

engine/engine/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	
	<%= f.label "First Name"  %>
  <%= f.text_field :fname, class: 'form-control' %>

	<%= f.label "Last Name" %>
  <%= f.text_field :lname, class: 'form-control' %>

  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

	<% if require_payment? && !@edit_user_page %>
		<%= f.label "Discount Code" %>
		<%= f.text_field :discount_code, class: 'form-control' %>
	<% end %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

engine/engine/app/views/users/_user.html.erb
<%= content_tag :li, class: 'searchable' do %>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.username, user %>
	<% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
		<br />
		<%= mail_to user.email %>
		<% if !user.paid? %>
			<%= content_tag :div, "Hasn't paid, created #{distance_of_time_in_words(user.created_at, Time.now)} ago.", class: "text-danger" %>
		<% elsif !user.activated? %>
			<%= content_tag :div, "Not Activated, created #{distance_of_time_in_words(user.created_at, Time.now)} ago.", class: "text-danger" %>
		<% else %>
			<%= content_tag :div, "User active.", class: "text-success" %>
		<% end %>
  <% end %>
<% end %>

engine/engine/app/views/users/checkout.html.erb
<% provide(:title, 'Checkout') %>

<%= content_tag :h1, 'Checkout' %>
<%= content_tag :div, class: 'row' do %>
	<%= content_tag :div, class: 'col-md-6 col-md-offset-3' do %>

		<div class="well">
			<div><strong>Name:</strong> <%= @user.fname %> <%= @user.lname %></div>
			<div><strong>Username:</strong> <%= @user.username %></div>
			<div><strong>E-Mail:</strong> <%= @user.email %></div>
			<div><strong>Date:</strong> <%= @user.created_at.localtime.strftime("%m/%d/%Y %I:%M %p") %></div>
		</div>

		<%= form_tag charge_path(@user) do %>
			<table class="table">
				<thead>
					<tr>
						<td>Qty.</td>
						<td>Item</td>
						<td class="text-right">Amount</td>
					</tr>
				</thead>
				<tbody>
					<tr> 
						<td>1.</td>
						<td>Registration for <%= competition_name %></td>
						<td class="text-right"><%= number_to_currency(@cost.to_f / 100) %>&nbsp;</td>
					</tr>
					<% if @discount != 0 %>
						<tr> 
							<td></td>
							<td>Discount with code: <%= @user.discount_code %></td>
							<td class="text-right text-danger">(<%= number_to_currency(@discount.to_f / 100) %>)</td>
						</tr>
					<% end %>
					<tr> 
						<td></td>
						<td class="text-right">Total:</td>
						<td class="text-right"><%= number_to_currency((@cost - @discount).to_f / 100) %>&nbsp;</td>
					</tr>
				</tbody>
			</table>

			<a href="#" onclick="window.print();return false;">Print</a> 
			<div class="row pull-right">
  			<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          			data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          			data-description="<%= competition_name %> Registration"
          			data-amount="<%= @cost %>"
          			data-locale="auto">
				</script>
			</div>
			<%= hidden_field_tag "user_id", :id, value: @user.id %>
  	<% end %>

  <% end %>
<% end %>

engine/engine/app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<%= content_tag :h1, 'Edit your profile' %>
<%= content_tag :div, class: 'row' do %>
	<%= content_tag :div, class: 'col-md-6 col-md-offset-3' do %>
		<%= render 'form' %>
		<%= content_tag :div, class: 'gravatar_edit' do %>
      <%= gravatar_for @user %>
			<%= link_to 'change', 'http://gravatar.com/emails', target: '_blank' %>
  	<% end %>
  <% end %>
<% end %>

engine/engine/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<%= content_tag :h1, 'All users' %>
<%= content_tag :h4, "Count: #{@users.count}", class: 'text-center' %>
<%= will_paginate %>

<%= content_tag :ul, class: 'users' do %>
	<%= render @users %>
<% end %>

<%= will_paginate %>

engine/engine/app/views/users/new.html.erb
<% provide(:title, "Sign up") %>

<% if require_payment? %>
	<% provide(:button_text, "Checkout") %>
<% else %>
	<% provide(:button_text, "Create my account") %>
<% end %>

<%= content_tag :h1, 'Sign Up' %>
<%= content_tag :div, class: 'row' do %>
	<%= content_tag :div, class: 'col-md-6 col-md-offset-3' do %>
		<%= render 'form' %>
  <% end %>
<% end %>

engine/engine/app/views/users/show.html.erb
<% provide(:title, @user.fname) %>
<%= content_tag :div, class: 'row' do %>
  <%= content_tag :aside, class: 'col-md-4' do %>
    <%= content_tag :section, class: 'user_info' do %>
      <%= content_tag :h1, class: 'text-right' do %>
        <%= gravatar_for @user %>
				<%= @user.username %>
      <% end %>
			<%= content_tag :h2, class: 'text-right' do %>
        <%= "#{@user.fname} #{@user.lname}" %>
				<%= tag :br %>
				<%= mail_to @user.email %>
			<% end %>
			<%= content_tag :p,  class: 'text-right' do %>
				<b>Hints:</b> <%= @number_of_hints %>, <b>Points:</b> <%= @score %>
			<% end %>
			<% if @user.team %>

				<% # Team Name and Score # %>
				<%= content_tag :hr %>
				<%= content_tag :h1, class: 'text-center' do %>
					<%= link_to @user.team.name, @user.team %> (<%= @user.team.get_score %>)
				<% end %>

				<% # Other Members # %>
				<%= content_tag :ul, class: 'users' do %>
					<%= render @user.team.users.where.not(id: @user.id) %>
				<% end %>

				<% # Leave button # %>
				<%= content_tag :p do %>
					<% if current_user?(@user) && @user.is_member?(@user.team) %>
						<%= link_to 'Leave', remove_member_path(user_id: @user.id, team_id: @user.team.id),  method: :post, class: 'btn btn-primary' %>
					<% end %>
				<% end %>

			<% else %>
				<% if current_user?(@user) %>
					<%= content_tag :p, 'You are not a member of a team.' %>
					<%= content_tag :p do %>
						<%= link_to 'Create', new_team_path, class: 'btn btn-primary' %>
						<%= link_to 'Join', teams_path, class: 'btn btn-primary' %>
					<% end %>
				<% else %>
					<%= content_tag :p, "#{@user.fname} does not belong to any team right now." %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>

	<% # User Stats # %>
	<%= content_tag :div, class: 'col-md-8 user_stats' do %>

		<%= javascript_tag do %>
			window.user_id = <%= @user.id %>;
		<% end %>
		
		<%= content_tag :div, "", id: 'user_accuracy',  class: 'col-sm-6', style: 'height:200px' %>
		<%= content_tag :div, "", id: 'user_categories',  class: 'col-sm-6', style: 'height:200px' %>

		<%= content_tag :h3, 'Correct Submissions', class: 'col-md-12 text-center' %>
		<%= content_tag :h5, "#{@accuracy * 100}% accuracy", class: 'text-center' %>
		<%= content_tag :ul do %>
			<%= render @submissions.where(correct: true) %>
		<% end %>
	<% end %>

<% end %>